# Generated by Django 4.2.6 on 2023-11-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="packages",
            fields=[
                (
                    "package_id",
                    models.AutoField(default=0, primary_key=True, serialize=False),
                ),
                ("p1_img", models.ImageField(upload_to="placess/")),
                ("p1_name", models.CharField(max_length=50)),
                ("p1_price", models.IntegerField(default=0)),
                ("trending", models.BooleanField(default=False)),
            ],
        ),
    ]
