# Generated by Django 4.2.6 on 2023-11-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour_app", "0005_alter_packages_seats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packages",
            name="seats",
        ),
        migrations.AddField(
            model_name="user_booking",
            name="seat_no",
            field=models.CharField(default=40, max_length=50),
        ),
    ]
