# Generated by Django 4.2.6 on 2023-11-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour_app", "0006_remove_packages_seats_user_booking_seat_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_booking",
            name="seat_no",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
