# Generated by Django 4.2.6 on 2023-11-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour_app", "0007_alter_user_booking_seat_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="packages",
            name="seats",
            field=models.CharField(default=50, max_length=50),
        ),
    ]
