# Generated by Django 4.2.6 on 2023-11-10 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tour_app", "0008_packages_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_booking",
            name="booking_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
