# Generated by Django 4.2.6 on 2023-11-10 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tour_app", "0009_user_booking_booking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_booking",
            name="booking_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
