# Generated by Django 4.2.6 on 2023-11-21 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tour_app", "0012_rename_product_cartitem_packages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="packages",
            new_name="package",
        ),
    ]
