# Generated by Django 4.2.6 on 2023-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour_app", "0014_rename_package_cartitem_packages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_booking",
            name="type",
            field=models.CharField(
                choices=[("Adults", "Adult"), ("child", "child")], max_length=50
            ),
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
