# Generated by Django 4.2.6 on 2023-12-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour_app", "0015_alter_user_booking_type_delete_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_booking",
            name="payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user_booking",
            name="payment_id",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
