# Generated by Django 4.2.6 on 2023-12-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour_app", "0016_user_booking_payment_user_booking_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_booking",
            name="user_img",
            field=models.ImageField(default=False, upload_to="userimg/"),
        ),
    ]
