# Generated by Django 5.0.3 on 2024-07-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0019_packages_from_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='from_place',
        ),
        migrations.AddField(
            model_name='packages',
            name='from_place',
            field=models.ManyToManyField(blank=True, null=True, to='tour_app.places'),
        ),
    ]
