# Generated by Django 5.0.3 on 2024-07-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0020_remove_packages_from_place_packages_from_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_booking',
            name='from_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_app.places'),
        ),
    ]
