# Generated by Django 5.0.3 on 2024-07-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0021_user_booking_from_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
