# Generated by Django 5.0.3 on 2024-07-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0023_user_booking_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_booking',
            name='ticket_expair',
            field=models.BooleanField(default=False),
        ),
    ]
