# Generated by Django 5.0.3 on 2024-07-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0024_user_booking_ticket_expair'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='is_pack_available',
            field=models.BooleanField(default=False),
        ),
    ]
