# Generated by Django 5.0.3 on 2024-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0025_packages_is_pack_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='is_pack_available',
            field=models.BooleanField(default=True),
        ),
    ]
