# Generated by Django 5.0.3 on 2024-07-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0026_alter_packages_is_pack_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='seat_counts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
